### ISSUE TITLE
caveexpress: Map second ice 04 never spawns any package

### ISSUE THREAD

**Issue by apoleon** [mgerhardy/caveexpress#100]
Hi,

I'm hereby forwarding Debian bug 

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=847147

Apparently in this map a package is never spawned, so it is impossible to continue the game and move forward.

Is there a way to skip maps and to play a map directly without having to complete earlier levels first (aka cheats) ?

**Comment by mgerhardy** [comment]
There is a command "finish" - but only in debug builds. You can open the console (shift+tab) and just type "finish" while the map is loaded.

other than that, you might want to try "map ice-05" in the console.

This is not reproducible in a debug build - will check it out in a release build once I'm at home again.

Btw. type "listmaps" to get a full list of registered maps.
