### ISSUE TITLE
Appstream metadata uses legacy format

### ISSUE THREAD

**Issue by apoleon** [mgerhardy/caveexpress#103]
Hi,

the provided appstream.xml file is a bit outdated and uses the legacy format. This might prevent caveexpress from showing up in some software centers. I have used the appstreamcli validate command to find and correct some of the obsolete tags. More information about the new specification can be found at

https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#sect-Metadata-GenericComponent

Please find attached a possible solution.

[valid-appdata.txt](https://github.com/mgerhardy/caveexpress/files/1546096/valid-appdata.txt)

**Comment by apoleon** [comment]
Ah, I forgot one thing. appdata.xml should be installed into /usr/share/metainfo from now on.

**Comment by mgerhardy** [comment]
Thanks for reporting - should be fixed.
