### ISSUE TITLE
On Linux, Cmake stop with "No package 'gtest' found"

### ISSUE THREAD

**Issue by goupildb** [mgerhardy/caveexpress#104]
I'm on 32-bits Linux Debian Sid
I have install the packages libbox2d-dev libyajl-dev libglm-dev libgtest-dev libsqlite3-dev liblua5.2-dev zlib1g-dev binutils-dev libncurses5-dev libsdl2-dev libsdl2-net-dev libsdl2-image-dev libsdl2-mixer-dev
When i try to compile with : $ cmake .
(...)
-- Checking for gtest
-- Checking for module 'gtest'
--   No package 'gtest' found
(...)
but libgtest-dev is installed (i have verified on my package manager, synaptic)

**Comment by mgerhardy** [comment]
gtest is just for the unittest. Last time I checked it was packaged as sourcefiles in debian. There is a bundled version - so it should be safe to ignore that warning.

**Comment by goupildb** [comment]
Problem, this error stop cmake  :
(...)
-- Checking for gtest
-- Checking for module 'gtest'
--   No package 'gtest' found
-- Could NOT find gtest (missing: GTEST_INCLUDE_DIRS GTEST_LIBRARIES) 
-- No system wide installation found, use built-in version of gtest
-- wrote /mnt/DDprc/Download/caveexpress-0.1-999/cavepacker-files.h.in
-- build complete.lua: /mnt/DDprc/Download/caveexpress-0.1-999/contrib/assets/png-packed/cavepacker
-- /usr/bin/luac found
-- wrote /mnt/DDprc/Download/caveexpress-0.1-999/tests_cavepacker-files.h.in
-- wrote /mnt/DDprc/Download/caveexpress-0.1-999/caveexpress-files.h.in
-- build complete.lua: /mnt/DDprc/Download/caveexpress-0.1-999/contrib/assets/png-packed/caveexpress
-- /usr/bin/luac found
-- wrote /mnt/DDprc/Download/caveexpress-0.1-999/tests_caveexpress-files.h.in
-- build complete.lua: /mnt/DDprc/Download/caveexpress-0.1-999/contrib/assets/png-packed/tests
-- wrote /mnt/DDprc/Download/caveexpress-0.1-999/tests-files.h.in
-- Configuring incomplete, errors occurred!
See also "/mnt/DDprc/Download/caveexpress-0.1-999/CMakeFiles/CMakeOutput.log".
See also "/mnt/DDprc/Download/caveexpress-0.1-999/CMakeFiles/CMakeError.log".

The last lines in CMakeError.log are :
(...)
Source file was:

          #include <pthread.h>
          #include <pthread_np.h>
          int main(int argc, char** argv) { return 0; }
Determining if the function pthread_set_name_np exists failed with the following output:
Change Dir: /mnt/DDprc/Download/caveexpress-0.1-999/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_e5299/fast"
/usr/bin/make -f CMakeFiles/cmTC_e5299.dir/build.make CMakeFiles/cmTC_e5299.dir/build
make[1] : on entre dans le répertoire « /mnt/DDprc/Download/caveexpress-0.1-999/CMakeFiles/CMakeTmp »
Building C object CMakeFiles/cmTC_e5299.dir/CheckFunctionExists.c.o
/usr/bin/cc   -g -Wcast-qual -Wcast-align -Wpointer-arith -Wno-long-long -Wno-multichar -Wshadow -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wreturn-type -Wwrite-strings -Wno-variadic-macros -Wno-unknown-pragmas -pthread -DCHECK_FUNCTION_EXISTS=pthread_set_name_np -D_REENTRANT -pthread   -o CMakeFiles/cmTC_e5299.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.9/Modules/CheckFunctionExists.c
Linking C executable cmTC_e5299
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_e5299.dir/link.txt --verbose=1
/usr/bin/cc  -g -Wcast-qual -Wcast-align -Wpointer-arith -Wno-long-long -Wno-multichar -Wshadow -Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wreturn-type -Wwrite-strings -Wno-variadic-macros -Wno-unknown-pragmas -pthread -DCHECK_FUNCTION_EXISTS=pthread_set_name_np -D_REENTRANT -pthread    -rdynamic CMakeFiles/cmTC_e5299.dir/CheckFunctionExists.c.o  -o cmTC_e5299 
CMakeFiles/cmTC_e5299.dir/CheckFunctionExists.c.o : Dans la fonction « main » :
/usr/share/cmake-3.9/Modules/CheckFunctionExists.c:17 : référence indéfinie vers « pthread_set_name_np »
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_e5299.dir/build.make:97 : la recette pour la cible « cmTC_e5299 » a échouée
make[1]: *** [cmTC_e5299] Erreur 1
make[1] : on quitte le répertoire « /mnt/DDprc/Download/caveexpress-0.1-999/CMakeFiles/CMakeTmp »
Makefile:126 : la recette pour la cible « cmTC_e5299/fast » a échouée
make: *** [cmTC_e5299/fast] Erreur 2

I had already test the compilation with the following packages installed :
libxorg-gtest-dev
libxorg-gtest-data
cmake-extras
and the result was the same : same error when trying to compile

**Comment by mgerhardy** [comment]
There must be another problem - can you post the whole cmake configure log?

**Comment by goupildb** [comment]
Sorry for the delay of my answer, I had not seen this message
[CMakeError.log](https://github.com/mgerhardy/caveexpress/files/1891144/CMakeError.log)
[CMakeOutput.log](https://github.com/mgerhardy/caveexpress/files/1891146/CMakeOutput.log)
Is it the good files you need ?

**Comment by mgerhardy** [comment]
Thanks for the logs. They might help later on - but first I would need the output of this:
```
mkdir build;
cd build;
cmake .. > cmakelogfile.txt 2>&1
```

**Comment by goupildb** [comment]
Here is the file :
[cmakelogfile.txt](https://github.com/mgerhardy/caveexpress/files/1904391/cmakelogfile.txt)

**Comment by mgerhardy** [comment]
Ah, it's box2d related. Do you have libbox2d-dev installed on your system? Which version?

**Comment by goupildb** [comment]
Yes, libbox2d-dev v. 2.3.1+ds-4 on Debian Sid

**Comment by mgerhardy** [comment]
Should be fixed in latest master. Feedback would be welcome. Thanks for your detailed report and your time.

**Comment by goupildb** [comment]
I have tested the 062e19e commit, it don't fixed this issue.

[CMakeError.log](https://github.com/mgerhardy/caveexpress/files/1921046/CMakeError.log)
[CMakeOutput.log](https://github.com/mgerhardy/caveexpress/files/1921047/CMakeOutput.log)
[cmakelogfile.txt](https://github.com/mgerhardy/caveexpress/files/1921057/cmakelogfile.txt)

**Comment by mgerhardy** [comment]
Thanks for the feedback. Did another attempt.

**Comment by goupildb** [comment]
Thank you too for your games and your help.
I have tested the 5f7755f commit, and it compiles well!
[CMakeError.log](https://github.com/mgerhardy/caveexpress/files/1925144/CMakeError.log)
[CMakeOutput.log](https://github.com/mgerhardy/caveexpress/files/1925145/CMakeOutput.log)
[cmakelogfile.txt](https://github.com/mgerhardy/caveexpress/files/1925153/cmakelogfile.txt)

It produces caveexpress and cavepacker binaries, but when I run one or the other, it displays 
$ ./caveexpress
==8552==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.

Do I need to install the binary or data in a particular place for it to find?
I do not know what to do

**Comment by mgerhardy** [comment]
Oh, that's the clang address sanitizer. I've disabled it by default now in latest master.

**Comment by mgerhardy** [comment]
3603b84d2cef68e1324ce63a3bc6a822c52c3bee

**Comment by goupildb** [comment]
It works well
Thank you very much
Solved
