### ISSUE TITLE
LIBS: src/libs/gtest should be removed from the source tarball

### ISSUE THREAD

**Issue by apoleon** [mgerhardy/caveexpress#12]
We have already discussed this library but I now think that this one can be omitted from the source tarball as well. Debian and other distributions already provide the same files as a -dev package and since caveexpress does not link in any way against a shared version of gtest, src/libs/gtest can be successfully replaced by Debian's version of gtest and code duplication can be avoided

**Comment by mgerhardy** [comment]
I don't really think that I can remove the gtest source from the source tarball, because windows users and mac users would not be able to compile the package anymore. And this should work out-of-the-box.
