### ISSUE TITLE
Switching the build system to cmake

### ISSUE THREAD

**Issue by apoleon** [mgerhardy/caveexpress#13]
This issue is for tracking the status of switching to another build system.

It would be great if it were possible to build caveexpress and cavepacker and the corresponding HTML5 versions in one step by configuring build flags to build either one of them or all together without having to call the configure or build targets multiple times in a row as it is currently the case.

**Comment by mgerhardy** [comment]
started the conversion with 626e5566af45e6b309c7f087d42a0d05ba4ffa85

**Comment by mgerhardy** [comment]
The conversion is now done - I will close this issue now. If there are still issues left, please open new issues.
