### ISSUE TITLE
Adding man pages for caveexpress and cavepacker

### ISSUE THREAD

**Issue by apoleon** [mgerhardy/caveexpress#15]
I think having man pages for caveexpress and cavepacker would be useful. I intend to provide patches soon.

**Comment by apoleon** [comment]
It seems there are not many command line options yet. So here is the initial man page for caveexpress. I will update the file, if there are more options in the future.

https://gist.github.com/9acaacdd4a8445ecd9ed

**Comment by mgerhardy** [comment]
man pages for caveexpress and cavepacker are now in the repo
