### ISSUE TITLE
SDL 2.0.3 support

### ISSUE THREAD

**Issue by akien-mga** [mgerhardy/caveexpress#2]
Currently your configure script is looking for SDL_opengl_glext.h [1] to check for SDL2. The problem is that this header is only part of the current development branch of SDL2, it's not included in the latest stable release, SDL 2.0.3.

I just wanted to check whether this is a strict requirement (in which case it could be good to state it in the README) or if you just used this header to make sure that you find SDL2 and not SDL 1.2?
If it's the latter, it would be nice to find a better solution since the current build system is broken with stable SDL2.

[1] https://github.com/mgerhardy/caveexpress/blob/master/configure#L265

**Comment by mgerhardy** [comment]
Unfortunately it is a strict requirement. I will add this to the readme. But you can also just use the embedded sdl version:
./configure --with-embedded-sdl2

**Comment by mgerhardy** [comment]
2.0.4 should be available very soon btw. then this is no longer a problem.

**Comment by mgerhardy** [comment]
I've added a Requirements section to the readme

**Comment by akien-mga** [comment]
Thanks! :-)

**Comment by akien-mga** [comment]
> 2.0.4 should be available very soon btw. then this is no longer a problem.

"Soon" took longer than expected, but SDL 2.0.4 finally got released! I'll restart my work on packaging Cave Express for Mageia :)

**Comment by mgerhardy** [comment]
Cool - don't forget CavePacker btw. ;) And please let me know about the status - I would like to link it from the homepage.
