### ISSUE TITLE
Gameplay physics regression

### ISSUE THREAD

**Issue by petevine** [mgerhardy/caveexpress#20]
Dropping packages makes them stop in mid-air above ground and if very close to the shredder they continue in a slow-motion jerky movement towards it. 
It seems something broke not more than 10 days ago - when I first had a look at the game around that time on x86 all was well.

**Comment by mgerhardy** [comment]
Thanks a lot - this also is floating point related - box2d uses float internally for everything, I remember that I once had a problem with the fast-math switch. I've removed it from master - which exact revision did you try?

**Comment by mgerhardy** [comment]
see a2026ff97edff1b84fb02e1f36da01d82fab19e7

**Comment by mgerhardy** [comment]
removed again (after cmake conversion) in dfa0ccc46cbd09813077063e982f100fcd97831f

**Comment by petevine** [comment]
I have no idea, I've simply downloaded a snapshot a few times over that period.

**Comment by petevine** [comment]
Oh, I've just realised you must be mattn from ufoai that I'm also trying to get to work on Odroid. Kudos!

**Comment by mgerhardy** [comment]
yes, I am.

So I can assume you tried latest master (after the above mentioned commit from yesterday) and it is still not working?

**Comment by petevine** [comment]
No, it's fixed now.
