### ISSUE TITLE
Resuming maps doesn't work

### ISSUE THREAD

**Issue by petevine** [mgerhardy/caveexpress#21]
On the first run it's possible to finish a number of successive maps without a problem.
Exiting and trying to resume the last map does nothing except for playing the click sound.
 
For example:
INFO: INFO (LOG_CAMPAIGN): start map introducing-03-tree
INFO: INFO (LOG_MAP): load map introducing-03-tree
INFO: INFO (LOG_LUA):  (null): [string "maps/introducing-03-tree.lua"] -1
INFO: INFO (LOG_LUA):  (null): [string "maps/introducing-03-tree.lua"] 3
INFO: INFO (LOG_LUA):  (null): [string "maps/introducing-03-tree.lua"] 1
INFO: INFO (LOG_LUA):  (null): [string "maps/introducing-03-tree.lua"] 6
INFO: INFO (LOG_LUA):  (null): [string "maps/introducing-03-tree.lua"] 5
INFO: INFO (LOG_LUA):  (null): [string "maps/introducing-03-tree.lua"] 179
INFO: INFO (LOG_LUA):  (null): [string "maps/introducing-03-tree.lua"] 8
INFO: INFO (LOG_LUA):  (null): [string "maps/introducing-03-tree.lua"] 179
INFO: INFO (LOG_LUA):  (null): [string "maps/introducing-03-tree.lua"] -1
INFO: INFO (LOG_LUA):  (null): [string "maps/introducing-03-tree.lua"] -1
INFO: INFO (LOG_LUA):  (null): [string "maps/introducing-03-tree.lua"] 2
INFO: INFO (LOG_LUA):  (null): [string "maps/introducing-03-tree.lua"] -1
INFO: INFO (LOG_SERVER): Load map with title introducing-03-tree
INFO: INFO (LOG_LUA):  (null): [string "maps/introducing-03-tree.lua"] -1
INFO: INFO (LOG_LUA):  (null): [string "maps/introducing-03-tree.lua"] 10
INFO: INFO (LOG_LUA): field get: [C] -1
INFO: INFO (LOG_LUA): field get: [C] -1
.
.
.
INFO: INFO (LOG_LUA):  (null): [string "maps/introducing-03-tree.lua"] 156
INFO: INFO (LOG_LUA): method addEmitter: [C] -1
INFO: INFO (LOG_LUA): method addEmitter: [C] -1
INFO: INFO (LOG_LUA):  (null): [string "maps/introducing-03-tree.lua"] 158
ERROR: ERROR (LOG_LUA): [string "maps/introducing-03-tree.lua"]:158: attempt to perform arithmetic on a nil value (global 'npc')
ERROR: ERROR (LOG_MAP): failed to load the map introducing-03-tree
INFO: INFO (LOG_BACKEND): failed to load map introducing-03-tree

**Comment by mgerhardy** [comment]
I will try to reproduce this - this looks again like the lua issue from #18 - thanks for providing a hint how to reproduce it. Will take a look.

**Comment by petevine** [comment]
I probably have no idea what I'm talking about but could the smaller stack size on those 32-bit systems be in any way related to the lua debug crashes?

**Comment by petevine** [comment]
One more thing I've just remembered - my first build on x86 was a debug one and even though it already had this particular issue, it didn't have the startup lua crash.  Two weeks ago tops.

**Comment by petevine** [comment]
I'm no longer able to reproduce.
