### ISSUE TITLE
Lua crash at startup (x86 & arm, release & debug)

### ISSUE THREAD

**Issue by petevine** [mgerhardy/caveexpress#27]
After showing the splash screen the game aborts:

INFO: (LOG_BACKEND): next init state: 1
INFO: (LOG_BACKEND): init frontend creation
INFO: (LOG_CLIENT): Use frontend sdl
INFO: (LOG_BACKEND): next init state: 2
INFO: (LOG_BACKEND): init sdl
INFO: (LOG_BACKEND): next init state: 3
INFO: (LOG_BACKEND): init frontend
INFO: (LOG_CLIENT): initializing: -1:-1 - fullscreen: true
INFO: (LOG_CLIENT): no joysticks found
INFO: (LOG_CLIENT): found 0 touch device(s)
INFO: (LOG_CLIENT): 0 haptic devices
INFO: (LOG_CLIENT): no rumble support
INFO: (LOG_CLIENT): current desktop mode: 1280x1024@59Hz (SDL_PIXELFORMAT_RGB888)
ERROR: (LOG_CLIENT): unknown error (/home/odroid/SDLFrontend.cpp:701 => virtual void SDLFrontend::setGLAttributes())
ERROR: (LOG_CLIENT): unknown error (/home/odroid/SDLFrontend.cpp:703 => virtual void SDLFrontend::setGLAttributes())
ERROR: (LOG_CLIENT): unknown error (/home/odroid/SDLFrontend.cpp:705 => virtual void SDLFrontend::setGLAttributes())
ERROR: (LOG_CLIENT): unknown error (/home/odroid/SDLFrontend.cpp:715 => virtual void SDLFrontend::setGLAttributes())
ERROR: (LOG_CLIENT): unknown error (/home/odroid/SDLFrontend.cpp:717 => virtual void SDLFrontend::setGLAttributes())
ERROR: (LOG_CLIENT): unknown error (/home/odroid/SDLFrontend.cpp:719 => virtual void SDLFrontend::setGLAttributes())
INFO: (LOG_CLIENT): doublebuffer: disabled
INFO: (LOG_CLIENT): available driver: x11
INFO: (LOG_CLIENT): available driver: mir
INFO: (LOG_CLIENT): available driver: dummy
INFO: (LOG_CLIENT): driver: x11
INFO: (LOG_CLIENT): found 1 display(s)
INFO: (LOG_CLIENT): init sdl renderer
INFO: (LOG_CLIENT): available renderer opengles2
INFO: (LOG_CLIENT): available renderer opengles
INFO: (LOG_CLIENT): available renderer software
INFO: (LOG_CLIENT): try sdl renderer: opengles2
INFO: (LOG_CLIENT): actual renderer opengles2
INFO: (LOG_CLIENT): max texture resolution: 4096:4096
INFO: (LOG_CLIENT): possible display modes:
INFO: (LOG_CLIENT): 1280x1024@59Hz SDL_PIXELFORMAT_RGB888
INFO: (LOG_CLIENT): actual resolution: 1280x1024
INFO: (LOG_CLIENT): destroy texture loading
INFO: (LOG_CLIENT): soundengine: sdl
INFO: (LOG_CLIENT): available audio driver pulseaudio
INFO: (LOG_CLIENT): available audio driver alsa
INFO: (LOG_CLIENT): available audio driver dsp
INFO: (LOG_CLIENT): available audio driver disk
INFO: (LOG_CLIENT): available audio driver dummy
ERROR: (LOG_CLIENT): Failed to initialize sdl mixer with ogg support
INFO: (LOG_CLIENT): actual audio driver: pulseaudio
INFO: (LOG_CLIENT): sound initialized
INFO: (LOG_BACKEND): next init state: 4
INFO: (LOG_BACKEND): init the serviceprovider
INFO: (LOG_NET): init the network layer
INFO: (LOG_GENERAL): switching to loopback
INFO: (LOG_NET): init the network layer (local)
INFO: (LOG_BACKEND): initialize the texture definition
INFO: (LOG_CLIENT): loaded 719 texture definitions
INFO: (LOG_MAP): loaded 104 maps
INFO: (LOG_COMMANDS): register command listmaps
INFO: (LOG_BACKEND): initialized the serviceprovider
INFO: (LOG_GENERAL): shutting down the network
INFO: (LOG_GENERAL): switching to loopback
INFO: (LOG_NET): init the network layer (local)
INFO: (LOG_BACKEND): next init state: 5
INFO: (LOG_BACKEND): init sprites
ERROR: (LOG_LUA): Lua panic. Error message: bad argument #-1 (number has no integer representation)
Aborted

I can see from the above log you are using the word 'actual' in the sense of 'current'. 
And btw, the **actual** log comes from arm/gles so the unknown frontend errors are not specific to this issue.

**Comment by mgerhardy** [comment]
this one should be fixed with ab4295d61e7e629f1bf374b278814854d987dfc5

thanks for reporting.

**Comment by petevine** [comment]
Yep, fixed. Thx!
And do please fix the error wording, it looks funny.
