### ISSUE TITLE
UI: Quit dialog usability

### ISSUE THREAD

**Issue by petevine** [mgerhardy/caveexpress#71]
Hi again,

Forgot to mention previously but immediately noticed again; the `'quit'` dialog is missing a question mark making it ambiguous compared to the `ok` button.

**Comment by mgerhardy** [comment]
I've added a question mark to the text/headline of the dialog - I hope that was what you meant?

**Comment by petevine** [comment]
Yes, that was it :)

**Comment by petevine** [comment]
BTW, remember your old project, ufoai? ;)

The gcc devs might need some help locating the problem during an [lto build of ufo on ARM](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69082). You probably know where to start better than anybody. Thx.
